# Generated by Django 6.0.1 on 2026-04-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_board_sessionrecording_stream_videoprogress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrecording',
            name='status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Uploaded'), (2, 'Processing'), (3, 'Transcoding'), (4, 'Finished'), (5, 'Error')], default=0),
        ),
    ]
