# Generated by Django 6.0.1 on 2026-04-20 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoprogress',
            old_name='updated_at',
            new_name='last_watched_at',
        ),
    ]
