server {
    listen 80;
    client_max_body_size 50M;

    # MAIN FRONTEND
    location / {
        root /usr/share/nginx/html/main;
        index index.html;
        try_files $uri /index.html;
    }

    # STUDENT
    location /student/ {
        alias /usr/share/nginx/html/student/;
        index index.html;
        try_files $uri /index.html;
    }

    # TEACHER
    location /teacher/ {
        alias /usr/share/nginx/html/teacher/;
        index index.html;
        try_files $uri /index.html;
    }

    # DJANGO API
    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_request_buffering off;
    }

    # STATIC
    location /static/ {
        alias /static/;
    }

    # MEDIA
    location /media/ {
        alias /media/;
    }

}
