# Generated by Django 6.0.1 on 2026-04-12 22:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='subject_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='subject_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('ASSIGNMENT', 'Assignment'), ('QUIZ', 'Quiz'), ('SESSION', 'Live Session'), ('SUBMISSION', 'Submission')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['subject_id'], name='activity_ac_subject_89eb83_idx'),
        ),
    ]
