# Generated by Django 6.0.1 on 2026-04-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_alter_quizattempt_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='quiz',
            name='quizzes_qui_due_dat_3b60ae_idx',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
